### ISSUE TITLE
Fix render/compile API

### ISSUE THREAD

**Issue by TimothyGu** [jstransformers/jstransformer-swig#1]
@RobLoach, you should probably directly map `exports.compile` to `swig.compile` as they completely map (`compile(str, options)`). `render` and friends are automatically provided by jstransformer if `compile` is set correctly.

**Comment by RobLoach** [comment]
Haha, since I merged the pull request that brought in the latest from Boilerplate, this issue was closed since it referenced #1. You meant #1 from Boilerplate, but it referenced this.
