### ISSUE TITLE
Switch to swig-templates

### ISSUE THREAD

**Issue by ghost** [jstransformers/jstransformer-swig#14]
This fork can be npm installed: https://github.com/node-swig/swig-templates. Might be a better option (By the way, the git url in this library's package.json points to jstransformer-foo).

**Comment by RobLoach** [comment]
Good find. Open source wins again. We could update it, and then issue a major version bump.

**Comment by ghost** [comment]
> Good find. Open source wins again. We could update it, and then issue a major version bump.

Yeah I think that would be a nice fix. Because the currently used fork doesn't seem to be actively maintained. But on that note, I don't know if there are other forks that are more popular, because you wouldn't want to have to switch again. This is just the best one I could find.

**Comment by RobLoach** [comment]
Sent up our forked fix https://github.com/node-swig/swig-templates/pull/47

**Comment by ghost** [comment]
Cool thanks! 🎉
